- name: Run Postman Collection
        run: |
          postman collection run \
            --collection "4a5de696-c0de-4b66-8962-21c099d12fcd" \
            --reporters cli,junit \
            --reporter-junit-export "test-results/junit.xml"
